import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import axios from 'axios';
import dynamic from 'next/dynamic'
import { style } from 'd3';
const Chart = dynamic(() => import('react-apexcharts'), { ssr: false });

const ChartData = {
  options: {
    chart: {
      type: 'candlestick',
      height: 350
    },
    title: {
      text: 'Stock Histoy',
      align: 'left'
    },
    xaxis: {
      type: 'datetime'
    },
    yaxis: {
      tooltip: {
        enabled: true
      }
    }
  },
};
const round = (num) => {
  return num ? num.toFixed(2) : null;
}

export default function Market() {
  // get data from query params
  const { id } = useRouter().query;
  const [data, setData] = useState([]);
  const [marketdata, setMarketdata] = useState([]);
  const [stockData, setStockData] = useState([{
    data: [],
  }]);

  useEffect(() => {
    if (id) {
    (async () => {
      const res = await axios.get(
        `https://localhost:5000/v1/api/iserver/marketdata/history?conid=${id}`
      );
      console.log(res.data);
      setData(res.data);

      // get market data
      const dataPoint = res.data.data.map((item, idx) => ({
        x: new Date(item.t * 1000),
        y: [item.o, item.h, item.l, item.c, item.v],
      }))
      console.log(dataPoint);

      setStockData([{
        data: dataPoint,
      }]);
    })();
  }
  }, [id]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Market Data</h1>

      <div>
        <h2>{data.length}</h2>
      </div>

      <div className={styles.grid}>
      <div className={styles.card}>
        <code>{data.text}</code>
        <div className={styles.infoList}>
          <div className={styles.infoItem}>
            <div className={styles.infoItemTitle}>
              <span>High: {data.high}</span>
            </div>

            <div className={styles.infoItemContent}>
              <span>Low: {data.low}</span>
            </div>

            <div className={styles.infoItemContent}>
              <span>timePeriod: {data.timePeriod}</span>
            </div>
          </div>
        </div>
      </div>
      </div>

      <div className={styles.Chart}>
      <Chart options={ChartData.options} series={stockData} type="candlestick" height={350} />
      </div>
    </div>
  );
}
