import { useState, useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import axios from 'axios';

export default function Home() {
  const [data, setData] = useState([]);
  const [stock, setStock] = useState([]);
  const [userInput, setUserInput] = useState('');

  const config = {
    mode: 'no-cors',
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Content-Type': 'application/json',
    },
  };

  useEffect(() => {
    async function fetchData() {
      const response = await axios.get(
        'https://localhost:5000/v1/api/portfolio/accounts'
      );
      console.log(response.data);
      setData(response.data[0]);
    }
    fetchData();
  }, []);

  const handleChange = (e) => {
    e.preventDefault();
    setUserInput(e.target.value);
  };

  const getMarketData = async (e) => {
    e.preventDefault();
    const res = await axios.get(
      `https://localhost:5000/v1/api/trsrv/stocks?symbols=${userInput}`
    );
    // convert object into array
    const stockData = Object.values(res.data);
    setStock(stockData[0]);
    console.log(stockData);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>IBKR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {data && (
        <div className={styles.hero} key={data.id}>
          <h1 className={styles.headerTitle}>{data.accountTitle}</h1>
          <div className={styles.card}>
            <code className={styles.code}>Accounts Infromation</code>
            <div className={styles.infoList}>
              <div className={styles.infoItem}>
                <div className={styles.infoItemTitle}>
                  <span>Account Number: {data.accountId}</span>
                </div>
                <div className={styles.infoItemContent}>
                  <span>Account Currency: {data.currency}</span>
                </div>

                <div className={styles.infoItemContent}>
                  <span>Trading Types: {data.tradingType}</span>
                </div>

                <div className={styles.infoItemContent}>
                  <span>Account Type: {data.type}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      <div className={styles.heroButtons}>
        <input type="search" name="query" onChange={handleChange} required />
        <button
          type="submit"
          onClick={getMarketData}
          className={styles.from_button}
        >
          Search
        </button>
      </div>

      <div className={styles.grid}>
        {stock &&
          stock.map((item) => (
            <div className={styles.card} key={item.length}>
              <p className={styles.cardTitle}>{item.name}</p>

              {item.contracts && ( // if the item has contracts
                <div className={styles.infoList}>
                  {item.contracts.map((contract) => (
                    <div className={styles.infoItem} key={contract.length}>
                      <div className={styles.infoItemTitle}>
                        <a href={contract.conid}>
                          Contract exchange: <code>{contract.exchange}</code>
                        </a>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          ))}
      </div>
    </div>
  );
}
